<?php

namespace sea2\astBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function getNotificationsForUser($userId)
    {
        $qb = $this->createQueryBuilder('n')
            ->select('n')
            ->where('n.user = :user_id')
            ->setParameter('user_id', $userId)
            ->addOrderBy('n.date', 'DESC');

        $notifications = $qb->getQuery()
            ->getResult();

        foreach($notifications as $notification){
            $notification->setDate($notification->getDate()->format('d-m-y'));
        }

        return $notifications;
    }
}
