<?php

namespace sea2\astBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackRepository extends EntityRepository
{
    public function getTracksForUser($userId)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.user = :user_id')
            ->setParameter('user_id', $userId)
            ->addOrderBy('t.date', 'DESC');

        $tracks = $qb->getQuery()
            ->getResult();

        foreach($tracks as $track){
            $track->setDate($track->getDate()->format('d-m-y'));
            $track->setStarttime($track->getStarttime()->format('h:m'));
            $track->setEndtime($track->getEndtime()->format('h:m'));
            $hours = (int)($track->getDuration()/3600);
            $seconds = $track->getDuration()%3600;
            $minutes = (int)($seconds/60);
            $seconds = $seconds%60;
            $track->setDuration($hours.':'.$minutes.':'.$seconds);
        }

        return $tracks;
    }

    public function getLatestTrack($userId)
    {
        $tracks = $this->getTracksForUser($userId);
        return $tracks[0];
    }
}
